version: '3.8'

services:
  pharmago-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: pharmago-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ngP@ssword!
    ports:
      - "11433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  pharmago-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: pharmago-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=pharmago-db;Database=PharmaDb;User Id=sa;Password=Str0ngP@ssword!
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"      # API available on localhost:5000
    depends_on:
      - pharmago-db
      - otlp-collector

  otlp-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otlp-collector
    ports:
      - "4317:4317"
      - "8889:8889"
    volumes:
      - ./Backend/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./Backend/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  pharmago-ui:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: pharmago-ui
    ports:
      - "4200:80"  # The Angular app will be available on localhost:4200
    depends_on:
      - pharmago-api

volumes:
  sql_data:
