name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: Código/Backend
      run: dotnet restore
    - name: Build
      working-directory: Código/Backend
      run: dotnet build --no-restore
    - name: Test
      working-directory: Código/Backend
      run: dotnet test --no-build --verbosity normal

  angular:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Compatible con Angular 14
    - name: Install dependencies
      working-directory: Código/Frontend
      run: npm install
    - name: Build Angular
      working-directory: Código/Frontend
      run: npm run build
    - name: Test Angular
      working-directory: Código/Frontend
      run: npm run test
