name: CI/CD PharmaGo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-back:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
   
    - name: Restore dependencies
      working-directory: ./Código/Backend/
      run: dotnet restore
   
    - name: Build
      run: dotnet build ./Código/Backend/PharmaGo.WebApi --configuration Release
   
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
   
    - name: Install frontend dependencies
      working-directory: ./Código/Frontend
      run: npm install

    - name: Build Angular
      working-directory: ./Código/Frontend
      run: npm run build --prod

    # Smoke test
    - name: Smoke Test
      working-directory: ./Código/Backend/PharmaGo.WebApi
      run: dotnet run
      
    # Unit tests and coverage
    - name: Test
      run: dotnet test ./Código/Backend/PharnaGo.Test --no-build --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate coverage report
      run: |
        reportgenerator \
          -reports:**/coverage.cobertura.xml \
          -targetdir:coveragereport \
          -reporttypes:Html
    
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coveragereport
